annotations:
  artifacthub.io/category: networking
apiVersion: v1
appVersion: 22.04.1
description: 'SRS enodeb '
home: https://github.com/Gradiant/charts
icon: https://pbs.twimg.com/profile_images/1153713220127006724/KfcRHyU-_400x400.jpg
keywords:
- network
- lte
- enodeb
maintainers:
- email: cgiraldo@gradiant.org
  name: cgiraldo
name: srs-enb
sources:
- https://github.com/srsLTE/srsLTE
version: 0.1.2
